import {QueryData} from "@supabase/supabase-js";
import {getClient} from "../model/getClient.ts";

const jewelryMasterQuery = getClient()
    .from('ar_jewelry_master')
    .select(`
            serial_number,
            sku_number,
            style_number,
            prod_name,
            msrp,
            cost,
            st_height,
            st_width,
            st_ctw,
            st_cost,
            st_ctw_range,
            st_table,
            age,
            gender,
            returnable,
            engravable,
            made_to_order,
            adjustable,
            repair_upgrade,
            configurator,
            multi_texture,
            multi_finish,
            bundle,
            status,
            date,
            id,
            variant_id,
            weight,
            material_type(metal_type),
            product_type(prod_code, product_type),
            stone_type(stone_type),
            st_source(source),
            stone_color(color),
            stone_shape(shape),
            stone_cut(cut),
            stone_orientation(orientation),
            stone_origin(origin),
            st_cert_type(cert_type),
            st_cert_cut(cut),
            metal_finish(finish),
            metal_texture(texture),
            band_style(style),
            band_width(width),
            jewelry_setting(setting),
            side_stones(stone),
            length(length),
            chain_type(type),
            pendant_type(type),
            earring_type(type),
            charm_type(type),
            ar_style(style)
    `)

export type JewelryMasterQuery = QueryData<typeof jewelryMasterQuery>;

const stoneMasterQuery = getClient()
    .from('ar_jewelry_master')
    .select(`
            serial_number,
            sku_number,
            style_number,
            prod_name,
            msrp,
            cost,
            st_height,
            st_width,
            st_ctw,
            st_cost,
            st_cert_num,
            st_ctw_range,
            st_table,
            memo, 
            stone_number,
            date,
            cat_status,
            stone_sku,
            refined_status,
            quantity,
            stone_product_type(prod_code),
            stone_type(stone_type),
            st_source(source),
            stone_color(color),
            stone_shape(shape),
            stone_cut(cut),
            stone_orientation(orientation),
            stone_origin(origin),
            st_cert_type(cert_type),
            st_cert_cut(cut),
            st_color_grade(grade),
            st_clarity_grade(grade)
    `)

export type StoneMasterQuery = QueryData<typeof stoneMasterQuery>;
