import {TablesInsert} from "./generatedDefinitions.ts";

export enum age {
    ADULT = "Adult"
}

export enum Status {
    ACTIVE = "active",
    ARCHIVED = "archived"
}

export enum gender {
    UNISEX = "unisex",
    MALE = "men",
    FEMALE = "women"
}

export enum ProductTypeIds {
    ENG = "ENG",
    WED = "WED",
    FJR = "FJR",
    NCK = "NCK",
    EAR = "EAR",
    BRA = "BRA",
    CHM = "CHM",
    ACC = "ACC",
    GFC = "GFC",
    FEE = "FEE",
    CON = "CON",
    OTH = "OTH"
}

export enum StoneProductTypeIds {
    ELS = "ELS",
    OLS = "OLS"
}

export enum ArJewelryMasterColumns {
    SERIAL_NUMBER = "Serial Number",
    TYPE = "Product Type",
    SKU = "SKU",
    STYLE_NUMBER = "Style Number",
    PRODUCT_NAME = "Product Name",
    MSRP = "MSRP",
    COST = "Cost",
    ST_TYPE = "ST Type",
    ST_SOURCE = "ST Source",
    ST_COLOR = "ST Color",
    ST_SHAPE = "ST Shape",
    ST_HEIGHT = "ST Height",
    ST_WIDTH = "ST Width",
    ST_ORIENTATION = "ST Orientation",
    ST_ORIGIN = "ST Origin",
    ST_CTW = "ST CTW",
    ST_COST_CT = "ST Cost/CT",
    ST_CERT_NUMBER = "ST Cert #",
    ST_CERT_CUT = "ST Cert Cut",
    ST_CUT = "ST Cut",
    ST_CERT_TYPE = "ST Cert Type",
    ST_CERT_COLOR = "ST Cert Color",
    ST_CERT_CLARITY = "ST Cert Clarity",
    AR_STYLE = "AR Style",
    AGE = "Age",
    GENDER = "Gender",
    RETURNABLE = "Returnable",
    ENGRAVABLE = "Engravable",
    MADE_TO_ORDER = "Made to Order",
    ADJUSTABLE = "Adjustable",
    MATERIAL_TYPE = "Material Type",
    METAL_FINISH = "Metal Finish",
    METAL_TEXTURE = "Metal Texture",
    BAND_STYLE = "Band Style",
    BAND_WIDTH = "Band Width",
    SETTING = "Jewelry Setting",
    SIDE_STONES = "Side Stones",
    LENGTH = "Length",
    CHAIN_TYPE = "Chain Type",
    PENDANT_TYPE = "Pendant Type",
    EARRING_TYPE = "Earring Type",
    CHARM_TYPE = "Charm Type",
    REPAIR_UPGRADE = "Repair/ Upgrade",
    CONFIGURATOR = "Configurator",
    MULTI_TEXTURE = "Multi-Texture",
    MULTI_FINISH = "Multi-Finish",
    BUNDLE = "Bundle",
    STATUS = "Status",
    DATE = "Date",
    ID = "ID",
    VARIANT_ID = "Variant ID",
    WEIGHT = "Weight",
}

export const MapFormDataToJewelryMasterColumns: { [key in ArJewelryMasterColumns]: keyof TablesInsert<'ar_jewelry_master'> } = {
    [ArJewelryMasterColumns.SERIAL_NUMBER]: 'serial_number',
    [ArJewelryMasterColumns.STYLE_NUMBER]: 'style_number',
    [ArJewelryMasterColumns.TYPE]: 'product_type',
    [ArJewelryMasterColumns.SKU]: 'sku_number',
    [ArJewelryMasterColumns.PRODUCT_NAME]: 'prod_name',
    [ArJewelryMasterColumns.MSRP]: 'msrp',
    [ArJewelryMasterColumns.COST]: 'cost',
    [ArJewelryMasterColumns.ST_TYPE]: 'st_type',
    [ArJewelryMasterColumns.ST_SOURCE]: 'st_source',
    [ArJewelryMasterColumns.ST_COLOR]: 'st_color',
    [ArJewelryMasterColumns.ST_SHAPE]: 'st_shape',
    [ArJewelryMasterColumns.ST_HEIGHT]: 'st_height',
    [ArJewelryMasterColumns.ST_WIDTH]: 'st_width',
    [ArJewelryMasterColumns.ST_ORIENTATION]: 'st_orientation',
    [ArJewelryMasterColumns.ST_ORIGIN]: 'st_origin',
    [ArJewelryMasterColumns.ST_CUT]: 'st_cut',
    [ArJewelryMasterColumns.ST_CTW]: 'st_ctw',
    [ArJewelryMasterColumns.ST_COST_CT]: 'st_cost',
    [ArJewelryMasterColumns.ST_CERT_TYPE]: 'st_cert_type',
    [ArJewelryMasterColumns.ST_CERT_NUMBER]: 'st_cert_type',
    [ArJewelryMasterColumns.ST_CERT_CUT]: 'st_cert_cut',
    [ArJewelryMasterColumns.ST_CERT_COLOR]: 'st_cert_color',
    [ArJewelryMasterColumns.ST_CERT_CLARITY]: 'st_cert_clarity',
    [ArJewelryMasterColumns.AR_STYLE]: 'ar_style',
    [ArJewelryMasterColumns.AGE]: 'age',
    [ArJewelryMasterColumns.GENDER]: 'gender',
    [ArJewelryMasterColumns.RETURNABLE]: 'returnable',
    [ArJewelryMasterColumns.ENGRAVABLE]: 'engravable',
    [ArJewelryMasterColumns.MADE_TO_ORDER]: 'made_to_order',
    [ArJewelryMasterColumns.ADJUSTABLE]: 'adjustable',
    [ArJewelryMasterColumns.MATERIAL_TYPE]: 'material_type',
    [ArJewelryMasterColumns.METAL_FINISH]: 'metal_finish',
    [ArJewelryMasterColumns.METAL_TEXTURE]: 'metal_texture',
    [ArJewelryMasterColumns.BAND_STYLE]: 'band_style',
    [ArJewelryMasterColumns.BAND_WIDTH]: 'band_width',
    [ArJewelryMasterColumns.SETTING]: 'jewelry_setting',
    [ArJewelryMasterColumns.SIDE_STONES]: 'side_stones',
    [ArJewelryMasterColumns.LENGTH]: 'length',
    [ArJewelryMasterColumns.CHAIN_TYPE]: 'chain_type',
    [ArJewelryMasterColumns.PENDANT_TYPE]: 'pendant_type',
    [ArJewelryMasterColumns.EARRING_TYPE]: 'earring_type',
    [ArJewelryMasterColumns.CHARM_TYPE]: 'charm_type',
    [ArJewelryMasterColumns.REPAIR_UPGRADE]: 'repair_upgrade',
    [ArJewelryMasterColumns.CONFIGURATOR]: 'configurator',
    [ArJewelryMasterColumns.MULTI_TEXTURE]: 'multi_texture',
    [ArJewelryMasterColumns.MULTI_FINISH]: 'multi_finish',
    [ArJewelryMasterColumns.BUNDLE]: 'bundle',
    [ArJewelryMasterColumns.STATUS]: 'status',
    [ArJewelryMasterColumns.DATE]: 'date',
    [ArJewelryMasterColumns.ID]: 'id',
    [ArJewelryMasterColumns.VARIANT_ID]: 'variant_id',
    [ArJewelryMasterColumns.WEIGHT]: 'weight',
};

export enum ArStoneMasterColumns {
    SERIAL_NUMBER = "Serial Number",
    SKU = "SKU-Number",
    TYPE = "ST Product Type",
    STYLE_NUMBER = "Style Number",
    PRODUCT_NAME = "Product Name",
    MSRP = "MSRP",
    COST = "Cost",
    ST_TYPE = "ST Type",
    ST_SOURCE = "ST Source",
    ST_COLOR = "ST Color",
    ST_SHAPE = "ST Shape",
    ST_CUT = "ST Cut",
    ST_HEIGHT = "ST Height",
    ST_WIDTH = "ST Width",
    ST_ORIENTATION = "ST Orientation",
    ST_ORIGIN = "ST Origin",
    ST_CTW = "ST CTW",
    ST_COST = "ST Cost",
    ST_CERT_TYPE = "ST Cert Type",
    ST_CERT_NUMBER = "ST Cert #",
    ST_CERT_CUT = "ST Cert Cut",
    ST_CERT_COLOR = "ST Cert Color",
    ST_CERT_CLARITY = "ST Cert Clarity",
    ST_CTW_RANGE = "ST CTW Range",
    ST_TABLE = "ST Table",
    MEMO = "Memo",
    STONE_NUMBER = "Stone Number",
    DATE = "Date",
    CAT_STATUS = "Cat Status",
    STONE_SKU = "Stone SKU",
    REFINED_STATUS = "Refined Status",
    QUANTITY = "Quantity",
    DATE_QUANTITY_ADDED = "Date Quantity Added"
}

export const MapFormDataToStoneMasterColumns: { [key in ArStoneMasterColumns]: keyof TablesInsert<'ar_stone_master'> } = {
    [ArStoneMasterColumns.SERIAL_NUMBER]: 'serial_number',
    [ArStoneMasterColumns.SKU]: 'sku_number',
    [ArStoneMasterColumns.STYLE_NUMBER]: 'style_number',
    [ArStoneMasterColumns.PRODUCT_NAME]: 'prod_name',
    [ArStoneMasterColumns.TYPE]: 'st_product_type',
    [ArStoneMasterColumns.MSRP]: 'msrp',
    [ArStoneMasterColumns.COST]: 'cost',
    [ArStoneMasterColumns.ST_TYPE]: 'st_type',
    [ArStoneMasterColumns.ST_SOURCE]: 'st_source',
    [ArStoneMasterColumns.ST_COLOR]: 'st_color',
    [ArStoneMasterColumns.ST_SHAPE]: 'st_shape',
    [ArStoneMasterColumns.ST_CUT]: 'st_cut',
    [ArStoneMasterColumns.ST_HEIGHT]: 'st_height',
    [ArStoneMasterColumns.ST_WIDTH]: 'st_width',
    [ArStoneMasterColumns.ST_ORIENTATION]: 'st_orientation',
    [ArStoneMasterColumns.ST_ORIGIN]: 'st_origin',
    [ArStoneMasterColumns.ST_CTW]: 'st_ctw',
    [ArStoneMasterColumns.ST_COST]: 'st_cost',
    [ArStoneMasterColumns.ST_CERT_TYPE]: 'st_cert_type',
    [ArStoneMasterColumns.ST_CERT_NUMBER]: 'st_cert_num',
    [ArStoneMasterColumns.ST_CERT_CUT]: 'st_cert_cut',
    [ArStoneMasterColumns.ST_CERT_COLOR]: 'st_cert_color',
    [ArStoneMasterColumns.ST_CERT_CLARITY]: 'st_cert_clarity',
    [ArStoneMasterColumns.ST_CTW_RANGE]: 'st_ctw_range',
    [ArStoneMasterColumns.ST_TABLE]: 'st_table',
    [ArStoneMasterColumns.MEMO]: 'memo',
    [ArStoneMasterColumns.STONE_NUMBER]: 'st_number',
    [ArStoneMasterColumns.DATE]: 'date',
    [ArStoneMasterColumns.CAT_STATUS]: 'cat_status',
    [ArStoneMasterColumns.STONE_SKU]: 'st_sku',
    [ArStoneMasterColumns.REFINED_STATUS]: 'refined_status',
    [ArStoneMasterColumns.QUANTITY]: 'quantity',
    [ArStoneMasterColumns.DATE_QUANTITY_ADDED]: 'date_quantity_added',
};

export enum LabeledInputType {
    STRING = "text",
    NUMBER = "number",
    DATETIME = "datetime-local",
    SELECT = "select"  // Add a type for select
}

//must be able to be converted into actual database table name with a .toLower().replace(/ /g, "_")
export enum AdminTables {
    AR_STYLE = "Ar Style",
    BAND_STYLE = "Band Style",
    BAND_WIDTH = "Band Width",
    CHAIN_TYPE = "Chain Type",
    CHARM_TYPE = "Charm Type",
    CTW_RANGE = "CTW Range",
    EARRING_TYPE = "Earring Type",
    JEWELRY_SETTING = "Jewelry Setting",
    LENGTH = "Length",
    MATERIAL_TYPE = "Material Type",
    METAL_FINISH = "Metal Finish",
    METAL_TEXTURE = "Metal Texture",
    PENDANT_TYPE = "Pendant Type",
    PRODUCT_TYPE = "Product Type",
    SIDE_STONES = "Side Stones",
    ST_CERT_CUT = "St Cert Cut",
    ST_CERT_TYPE = "St Cert Type",
    ST_CLARITY_GRADE = "St Clarity Grade",
    ST_COLOR = "St Color",
    ST_COLOR_GRADE = "St Color Grade",
    ST_CUT = "St Cut",
    ST_ORIENTATION = "St Orientation",
    ST_ORIGIN = "St Origin",
    ST_PRICE_RANGE = "St Price Range",
    ST_PRODUCT_TYPE = "St Product Type",
    ST_SHAPE = "St Shape",
    ST_SOURCE = "St Source",
    ST_TYPE = "St Type",
}
